### ISSUE TITLE
KeyError: 'sensor'

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/hass-browser_mod#106]
```
2020-06-11 12:27:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2892576496] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 76, in update
    self)
  File "/config/custom_components/browser_mod/helpers.py", line 30, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
```

showing after updating to version 29, double restarts and refresh cache multiple times...

also still seeing this:
```
2020-06-11 15:22:09 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2922472880] Received invalid command: browser_mod/connect
```

**Comment by holdestmade** [comment]
Same error here

Log Details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection.139685657268304
Source: custom_components/browser_mod/helpers.py:30
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 15:40:18 (1 occurrences)
Last logged: 15:40:18

Error handling message: Unknown error
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 76, in update
    self)
  File "/config/custom_components/browser_mod/helpers.py", line 30, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
```

**Comment by aaamoeder** [comment]
same here .. running latest HA and latest browser_mod

**Comment by ktownsend-personal** [comment]
Same for me. It seems to only occur when I restart Core. In every case I have an open browser. I suspect it wouldn't happen if there weren't any browsers open when I restart Core, but I haven't tried that yet.

**Comment by Mattie** [comment]
Same here :(

**Comment by emouawad** [comment]
Same Here

**Comment by davidrustingha** [comment]
Same here!

**Comment by gurbyz** [comment]
Same here.

**Comment by notherealmarco** [comment]
same error here

**Comment by KTibow** [comment]
If you enable the camera, it says the same thing but with `camera` instead as well.

**Comment by KTibow** [comment]
I changed the code, and it looks like the problem is in `[platform]`:
```python3
2020-08-31 14:48:48 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1847024152] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 72, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 32, in create_entity
    adder = adder[platform]
KeyError: 'sensor'
```

**Comment by aheath70** [comment]
Any news on this? I have the same error on HA 0.115.5.

**Comment by KTibow** [comment]
@aheath70 don't worry about it, it's just ugly. You can try to patch it yourself, but from what I've seen @thomasloven doesn't like to merge PRs for this repo.

**Comment by Mariusthvdb** [comment]
anyone know what's causing the error? Is it a user error (maybe not guarding a sensor) or is it a code issue in Browser-mod.

If the latter, @KTibow , how did you patch it. Maybe we can do so locally. 
It really is ugly indeed....

**Comment by KTibow** [comment]
Patched version (open /config/custom_components/browser_mod/helpers.py and replace the contents):
```
import logging

from homeassistant.helpers.entity import Entity, async_generate_entity_id

from .const import DOMAIN, DATA_DEVICES, DATA_ALIASES, DATA_ADDERS, CONFIG_DEVICES, DATA_CONFIG, CONFIG_PREFIX, CONFIG_DISABLE, CONFIG_DISABLE_ALL

_LOGGER = logging.getLogger(__name__)

def get_devices(hass):
    return hass.data[DOMAIN][DATA_DEVICES]

def get_alias(hass, deviceID):
    for k,v in hass.data[DOMAIN][DATA_ALIASES].items():
        if v == deviceID:
            return k
    return None

def get_config(hass, deviceID):
    config = hass.data[DOMAIN][DATA_CONFIG].get(CONFIG_DEVICES, {})
    return config.get(deviceID, config.get(deviceID.replace('-','_'), {}))

def create_entity(hass, platform, deviceID, connection):
    conf = get_config(hass, deviceID)
    if conf and (platform in conf.get(CONFIG_DISABLE, [])
        or CONFIG_DISABLE_ALL in conf.get(CONFIG_DISABLE, [])):
        return None
    if not conf and (platform in hass.data[DOMAIN][DATA_CONFIG].get(CONFIG_DISABLE, [])
        or CONFIG_DISABLE_ALL in hass.data[DOMAIN][DATA_CONFIG].get(CONFIG_DISABLE, [])):
        return None
    adder = hass.data[DOMAIN][DATA_ADDERS]
    if platform in adder:
        adder = adder[platform]
        entity = adder(hass, deviceID, connection, get_alias(hass, deviceID))
        return entity

def setup_platform(hass, config, async_add_devices, platform, cls):
    def adder(hass, deviceID, connection, alias=None):
        entity = cls(hass, connection, deviceID, alias)
        async_add_devices([entity])
        return entity
    if platform in hass.data[DOMAIN][DATA_ADDERS]:
        hass.data[DOMAIN][DATA_ADDERS][platform] = adder
    return True

class BrowserModEntity(Entity):

    def __init__(self, hass, connection, deviceID, alias=None):
        self.hass = hass
        self.connection = connection
        self.deviceID = deviceID
        self._data = {}
        prefix = hass.data[DOMAIN][DATA_CONFIG].get(CONFIG_PREFIX, '')
        self.entity_id = async_generate_entity_id(self.domain+".{}", alias or f"{prefix}{deviceID}", hass=hass)

    def updated(self):
        pass

    @property
    def data(self):
        return self._data
    @data.setter
    def data(self, data):
        self._data = data
        self.updated()

    @property
    def device_id(self):
        return self.deviceID

    def send(self, command, **kwargs):
        self.connection.send(command, **kwargs)
```

**Comment by Mariusthvdb** [comment]
thx, will have a go (though I haven't seen the error since on 115.5, which might have been luck ;-) ) As long as we dont really know why this happened, we wont be able to prevent it from user side errors...

**Comment by Mariusthvdb** [comment]
back from testing the above hack by @KTibow : unfortunately it made all previously created entities (media_player, light, sensor) disappear. It took 2 days for me to realize.... mostly only use the mobile device as media player, for my intercom messages, which stopped working.

Having now re-instated the original, immediately all entities are back.

Also, I havent seen the error this topic has as its subject.... so, should I close it for now? Anyone else still seeing this? I am using HA 115.6 now

**Comment by KTibow** [comment]
I don't use browser_mod anymore so I didn't realize that, and I don't know whether this is fixed.

**Comment by IDmedia** [comment]
The issue still persists in the latest version of HA for me.

**Comment by poudenes** [comment]
in HA 0.115.6 i have still same issue:

```
2020-10-05 11:40:37 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.3989803840] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 72, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 30, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
```

**Comment by poudenes** [comment]
Updated to 0.116.0 and now I see many of those errors:

```
2020-10-08 08:08:21 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.4010250880] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 72, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 30, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
2020-10-08 08:09:20 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.4017419624] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 72, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 30, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
2020-10-08 08:09:20 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.4017419624] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 72, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 30, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
2020-10-08 08:09:23 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.4010253160] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 72, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 30, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
2020-10-08 08:09:25 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.4010253160] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 72, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 30, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
2020-10-08 08:09:25 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.4010253160] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 72, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 30, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
2020-10-08 08:09:25 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.4010253160] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 72, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 30, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
2020-10-08 08:09:27 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.4010253160] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 72, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 30, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
2020-10-08 08:09:55 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.4010253160] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 72, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 30, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
2020-10-08 08:09:55 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.4010253160] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 72, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 30, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
```

**Comment by thomasloven** [comment]
> @aheath70 don't worry about it, it's just ugly. You can try to patch it yourself, but from what I've seen @thomasloven doesn't like to merge PRs for this repo.

Oh I do, I'm just really **really** bad at it, and currently a bit overloaded at work.

I plan to get back to maintaining my stuff soon, but I've been knowingly ignoring it for a while to avoid exhaustion.

**Comment by Mariusthvdb** [comment]
dont worry, please take your time. If anything we need a true fix, and not a hack like the one above, that kille browser-mod functionality completely ;-(

glad you're on it, we will hold.

**Comment by davidrustingha** [comment]
You are a hero mate

**Comment by poudenes** [comment]
Great!!
now I see a new line after reboot HA:

`2020-10-22 11:30:56 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.3965813688] Received invalid command: browser_mod/connect`

cleared cache didn't work

**Comment by julienlarivee** [comment]
Hi,
I still got the error. Anything I have to do to fix it?

I'm on :
Browser_mod 1.3.0
Home Assistant OS 5.12
core-2021.3.3
supervisor-2021.03.6

Error message:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 83, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'

**Comment by Mariusthvdb** [comment]
yes, it is still there, but suspect Thomas knows of this, and will eventually get to fixing it properly.

**Comment by Mariusthvdb** [comment]
thank you very much! so nice to have a clean startup log, you've finally clinched it. much appreciated!

**Comment by Mariusthvdb** [comment]
now notice the mentioned error:
```
2020-06-11 15:22:09 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2922472880] Received invalid command: browser_mod/connect
```
is still going strong.....

**Comment by Mariusthvdb** [comment]
Must admit to still see the
 ```
2022-02-19 16:19:16 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548170063984] Received invalid command: browser_mod/update
.....
2022-02-19 16:19:23 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548170063984] Received invalid command: browser_mod/update
2022-02-19 16:19:28 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548170063984] Received invalid command: browser_mod/update
```

tbh, I hadnt been paying attention to it, so I can not be precise about when this re-appeared.

@thomasloven do we need to re-open this? Or is the error on your radar elsewhere.
