### ISSUE TITLE
Error handling message: Unknown error

### ISSUE THREAD

**Issue by SentryMax** [thomasloven/hass-browser_mod#107]
After the last Home Assistant 0.111.4 update I get this error every time I restart HA

Logger: homeassistant.components.websocket_api.http.connection.281472883457744
Source: custom_components/browser_mod/helpers.py:10
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:21:20 AM (8 occurrences)
Last logged: 2:22:39 AM 

Error handling message: Unknown error

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 21, in handle_connect
    device = get_devices(hass).get(deviceID, BrowserModConnection(hass, deviceID))
  File "/config/custom_components/browser_mod/helpers.py", line 10, in get_devices
    return hass.data[DOMAIN][DATA_DEVICES]
KeyError: 'browser_mod'

**Comment by davidrustingha** [comment]
Can confirm, I have those errors too. I don’t experience an actual problem or something not working. It’s just the log that overflows with these.

**Comment by jaburges** [comment]
similar error here:
```Logger: homeassistant.components.websocket_api.http.connection.22471408318672
Source: custom_components/browser_mod/helpers.py:30
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 3:04:36 PM (1 occurrences)
Last logged: 3:04:36 PM

Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 76, in update
    self)
  File "/config/custom_components/browser_mod/helpers.py", line 30, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'```

**Comment by emouawad** [comment]
Same error

**Comment by holdestmade** [comment]
#106

**Comment by KTibow** [comment]
Mind closing?

**Comment by SentryMax** [comment]
Updated to 1.1.7 and restarted HA error now is this, got 2 of them.  the other error is no longer showing.
![BrowserMod](https://user-images.githubusercontent.com/57269475/96789325-3f02de80-13f5-11eb-926b-7f6a47d59b00.PNG)
