### ISSUE TITLE
Errors when HA restart and entities not ready

### ISSUE THREAD

**Issue by poudenes** [thomasloven/hass-browser_mod#159]
HA 0.117.1
Browser_mod: 1.2.3

When I restart my HA some sensors, or other things are not ready yet. Browser_mod report errors (sounds ok, but maybe not needed)

Maybe a idea to drop those errors alone until HA is full function?

```
2020-11-01 11:30:56 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.3950097192] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 83, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
2020-11-01 11:30:56 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.3950097192] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 92, in update
    self.media_player = self.media_player or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'media_player'
2020-11-01 11:30:56 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.3950097192] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 101, in update
    self.screen = self.screen or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'light'
2020-11-01 11:30:56 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.3950097192] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 83, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
2020-11-01 11:30:56 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.3951521976] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 92, in update
    self.media_player = self.media_player or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'media_player'
2020-11-01 11:30:56 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.3951521976] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 110, in update
    self.fully = self.fully or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'binary_sensor'
2020-11-01 11:30:56 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.3951521976] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 101, in update
    self.screen = self.screen or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'light'
2020-11-01 11:30:56 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.3951521976] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 83, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
2020-11-01 11:30:56 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.3951521976] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 83, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
```

**Comment by mcasper73** [comment]
I have the same problem with 116.4. **It's appeared after supervisor update to 2020.11.0.** 

@poudenes  have you got same version of supervisor ?

**Comment by fufar** [comment]
i have same errors on supervisor 2020.11.0 and 0.117.4 home assistant, really annoying

**Comment by mcasper73** [comment]
I solved it by inserting the line as below in configuration:
@poudenes @fufar 
homeassistant:
  legacy_templates: false

**Comment by KTibow** [comment]
@mcasper73 Where was this documented?

**Comment by poudenes** [comment]
> I solved it by inserting the line as below in configuration like in image.
> ![2020-11-06_164125](https://user-images.githubusercontent.com/16063061/98385198-0139c300-204f-11eb-98be-59662549201c.jpg)
> 
> @poudenes @fufar

didn't work for me

**Comment by poudenes** [comment]
Did someone solve this? Or is there a way so browser_mod will wait or retry to read the entities correct?

**Comment by KTibow** [comment]
This is a normal thing. `browser_mod` should work just fine.

**Comment by aladin2000** [comment]
same in 2021.2.1 
I did not try the legacy declaration.... 



Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
handler(self.hass, self, schema(msg))
File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
devices[deviceID].update(msg.get("data", None))
File "/config/custom_components/browser_mod/connection.py", line 83, in update
self.sensor = self.sensor or create_entity(
File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
2021-02-05 23:14:40 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1791831872] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
handler(self.hass, self, schema(msg))
File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
devices[deviceID].update(msg.get("data", None))
File "/config/custom_components/browser_mod/connection.py", line 92, in update
self.media_player = self.media_player or create_entity(
File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'media_player'
2021-02-05 23:14:40 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1791831872] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
handler(self.hass, self, schema(msg))
File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
devices[deviceID].update(msg.get("data", None))
File "/config/custom_components/browser_mod/connection.py", line 101, in update
self.screen = self.screen or create_entity(
File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'light'
2021-02-05 23:14:40 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1791831872] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
handler(self.hass, self, schema(msg))
File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
devices[deviceID].update(msg.get("data", None))
File "/config/custom_components/browser_mod/connection.py", line 83, in update
self.sensor = self.sensor or create_entity(
File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'

**Comment by KTibow** [comment]
Please format your code with the `<>` option.

**Comment by aladin2000** [comment]
> > I solved it by inserting the line as below in configuration like in image.
> > ![2020-11-06_164125](https://user-images.githubusercontent.com/16063061/98385198-0139c300-204f-11eb-98be-59662549201c.jpg)
> > @poudenes @fufar
> 
> didn't work for me

Same for me , did not work on 2021.2.1

**Comment by christopherdopp** [comment]
I am running the latest 2021.02.9 and I am getting a bunch of these exceptions in my logs. Does anybody have an idea of how to resolve them? They look like they are related to  the exceptions in this issue. 

```
2021-02-15 22:44:25 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472608557376] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
handler(self.hass, self, schema(msg))
File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
devices[deviceID].update(msg.get("data", None))
File "/config/custom_components/browser_mod/connection.py", line 98, in update
self.media_player.data = data.get('player')
File "/config/custom_components/browser_mod/helpers.py", line 106, in data
self.updated()
File "/config/custom_components/browser_mod/media_player.py", line 38, in updated
self.schedule_update_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 422, in schedule_update_ha_state
assert self.hass is not None
AssertionError
```

**Comment by KTibow** [comment]
Just googled that @christopherdopp, maybe this might be a bit relevant: https://github.com/StyraHem/ShellyForHASS/issues/341

**Comment by KTibow** [comment]
Still existent.

**Comment by thomasloven** [comment]
Please try release 1.3.1

**Comment by StefanoGiu** [comment]
Issue is still there...

**Comment by emufan** [comment]
Same with 2021.5.4. Tons of errors like this every second during startup:
```
2021-05-19 10:01:16 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140192571300112] Error handling message: Unknown error                                                                        
Traceback (most recent call last):                                                                                                                                                                                             
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 98, in async_handle                                                                                                                 
    handler(self.hass, self, schema(msg))                                                                                                                                                                                      
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update                                                                                                                                        
    devices[deviceID].update(msg.get("data", None))                                                                                                                                                                            
  File "/config/custom_components/browser_mod/connection.py", line 90, in update                                                                                                                                               
    self.sensor = self.sensor or create_entity(                                                                                                                                                                                
  File "/config/custom_components/browser_mod/helpers.py", line 49, in create_entity                                                                                                                                           
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]                                                                                                                                                                           
KeyError: 'sensor' 
```

**Comment by ttaidapos** [comment]
This is what I see.  Latest hass and broswer mod.

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/browser_mod/helpers.py:49
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:26:49 PM (2 occurrences)
Last logged: 1:26:50 PM

[2908406232] Error handling message: Unknown error
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/websocket_api/connection.py", line 98, in async_handle
    handler(self.hass, self, schema(msg))
  File "/home/homeassistant/.homeassistant/custom_components/browser_mod/connection.py", line 44, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/home/homeassistant/.homeassistant/custom_components/browser_mod/connection.py", line 90, in update
    self.sensor = self.sensor or create_entity(
  File "/home/homeassistant/.homeassistant/custom_components/browser_mod/helpers.py", line 49, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'`

**Followed by**
`Logger: homeassistant.components.webhook
Source: components/webhook/__init__.py:84
Integration: Webhook (documentation, issues)
First occurred: 1:26:51 PM (1 occurrences)
Last logged: 1:26:51 PM

Received message for unregistered webhook 5b3f491c3840aa6e512e92e43ac038a2e8fe67e1c0f307d715ef0aa02c78166d from 192.168.50.1`

**And**
`Logger: asyncio
Source: /usr/local/lib/python3.8/asyncio/selector_events.py:903
First occurred: 1:27:14 PM (22 occurrences)
Last logged: 1:27:14 PM

socket.send() raised exception.`

**Comment by browetd** [comment]
Same issue for me... and I run the last version of HA 2021.6.2... I run HA in debug mode for websocket.api, here is the output (including the line before and after the error)... I replaced some data by XXXX
`
2021-06-05 17:45:33 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [139687440822576] Received {'type': 'browser_mod/update', 'deviceID': 'XXXX', 'data': {'browser': {'path': '/lovelace/XXXX', 'visibility': 'visible', 'userAgent': 'Mozilla/5.0 (Linux; Android 10; Lenovo TB-X606F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.72 Safari/537.36', 'currentUser': 'XXXX', 'fullyKiosk': False, 'width': 1507, 'height': 943, 'battery_level': 51, 'charging': True, 'darkMode': False, 'userData': {'id': 'XXXX', 'name': 'XXXX', 'is_owner': False, 'is_admin': False, 'credentials': [{'auth_provider_type': 'homeassistant', 'auth_provider_id': None}], 'mfa_modules': [{'id': 'totp', 'name': 'Authenticator app', 'enabled': False}]}}}, 'id': 26}
2021-06-05 17:45:33 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139687440822576] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 100, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 90, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 49, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
2021-06-05 17:45:33 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [139687440822576] Sending {"id": 26, "type": "result", "success": false, "error": {"code": "unknown_error", "message": "Unknown error"}}
`

**Comment by Mariusthvdb** [comment]
+1
