### ISSUE TITLE
Error in core log after hassio core restart

### ISSUE THREAD

**Issue by riddik14** [thomasloven/hass-browser_mod#171]
My Home Assistant when I restart only core the log report error for browser_mod. If I restart all HassOs on rpi work good and no error in log. Why? Is normal?

**Comment by KTibow** [comment]
Which error did you get? Errors are normal.

**Comment by riddik14** [comment]
2020-12-17 19:21:03 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1861687184] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 83, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'

**Comment by KTibow** [comment]
This is expected behavior. Does it work?

**Comment by riddik14** [comment]
yes it work
