### ISSUE TITLE
Hacs will not load.

### ISSUE THREAD

**Issue by microfix** [thomasloven/hass-browser_mod#177]
Hey.

The HACS tells me that it will not load. 
The logs says something about the browser_mod, im not that into programming, so it can maby be my own fault. Hoper you can help me. :) 
Thanks in advance.
``
2021-01-12 10:06:50 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140421216802128] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
handler(self.hass, self, schema(msg))
File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
devices[deviceID].update(msg.get("data", None))
File "/config/custom_components/browser_mod/connection.py", line 83, in update
self.sensor = self.sensor or create_entity(
File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
``

**Comment by microfix** [comment]
HACS is startet after a while. And browser_mod still works. :/ Strange behavior

**Comment by KTibow** [comment]
This error is expected, see #159. Could you give a screenshot of
> The HACS tells me that it will not load.

**Comment by microfix** [comment]
Thanks. 

Been looking closer, Browser_mod do not give me any sensors og entitys, why is that. It's working and installed with hacs

**Comment by KTibow** [comment]
Did you configure it in `configuration.yaml`?

**Comment by theone11** [comment]
I am also getting these errors **_repeatedly_** in the log file during HA startup:

`
2021-01-14 20:19:48 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140242605794016] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 83, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
`

**Comment by theone11** [comment]
After recieving the errors (previous post) I uninstalled browser_mod via HACS (folder does not exist in custom_components anymore)

Now I get the following ERRORs (multiple entries) in the log file:

`
2021-01-14 23:07:53 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140255726299984] Received invalid command: browser_mod/update
`
