### ISSUE TITLE
Error handling message: Unknown error

### ISSUE THREAD

**Issue by StefanoGiu** [thomasloven/hass-browser_mod#216]
2021-04-27 15:45:56 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1789651969504] Error handling message: Unknown error
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\homeassistant\components\websocket_api\connection.py", line 97, in async_handle
    handler(self.hass, self, schema(msg))
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\custom_components\browser_mod\connection.py", line 42, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\custom_components\browser_mod\connection.py", line 83, in update
    self.sensor = self.sensor or create_entity(
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\custom_components\browser_mod\helpers.py", line 47, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'

**Comment by KTibow** [comment]
This is a normal message. Maybe @thomasloven should pin #159?

**Comment by StefanoGiu** [comment]
Why closed? The other one is also closed (159) without any solution!!!

**Comment by thomasloven** [comment]
159 is not closed
