### ISSUE TITLE
What is going on here?

### ISSUE THREAD

**Issue by criticallimit** [thomasloven/hass-browser_mod#255]
Have a lot of these in my Log. What can I do?

Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/entity.py:592 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 10. Oktober 2021, 9:16:27 (9239 occurrences) 
Last logged: 10:03:48

[547581366768] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 100, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
    self.updated()
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 592, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))  # type: ignore
AttributeError: 'NoneType' object has no attribute 'add_job'

**Comment by simpan** [comment]
I have similar error to, noticed it after 2021.10 update and latest browser_mod update (i think i updated this not to long ago)

ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140507187345872] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 100, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
    self.updated()
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 577, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))  # type: ignore
AttributeError: 'NoneType' object has no attribute 'add_job'

And it goes on and on

**Comment by simpan** [comment]
My problem was that i had disabled a device that was active, solved for me atleast

**Comment by maretodoric** [comment]
Is there any upgrade on improving this for easier tracking? This should be handled exception so that it can at least show us which device id is causing issues. I have 21 devices out of which i only use 1. I cannot seem to delete the other ones as  the delete is not implemented and my log file is being spammed. Pretty hard figuring out which device i need to make active to silence the message.

**Comment by roybosch** [comment]
```
Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/entity.py:643
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20 december 2021 09:55:59 (2311 occurrences)
Last logged: 11:03:04

[281472263937520] Error handling message: Unknown error
[281472252120992] Error handling message: Unknown error
[281472255159840] Error handling message: Unknown error
[281472673820096] Error handling message: Unknown error
[281472184637328] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 100, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
    self.updated()
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 643, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))  # type: ignore
AttributeError: 'NoneType' object has no attribute 'add_job'
```

Same problem here. I have no idea what causes this. What I do know is that I have this problem for months and that it doesn't seem to influence any functions.

**Comment by nielsfaber** [comment]
It occured to me as well.
I resolved it by locally editing the python files like so:
```python
    def updated(self):
        self.last_seen = datetime.now()
        if not self.hass: # added line
          return #added line
        self.schedule_update_ha_state()
```
The issue seems to be related to entities being removed from HA.

**Comment by vmcosco** [comment]
> This change needs to be made in `sensor.py`, `camera.py`, `media_player.py`, `binary_sensor.py`. The issue seems to be related to entities being removed from HA.

This fix worked for me as well.  Thanks

**Comment by jeremysherriff** [comment]
Shouldn't this be handled more globally, in either the instantiation of the entity or in the connection handler?  I'm not strong in python but it looks like this is just skipping an update, but if the entity is disabled we shouldn't interact with it at all.

**Comment by nielsfaber** [comment]
@jeremysherriff Yes, ofcourse. I just tried to get rid of the error to solve it for myself, it was not meant as a solution.
I don't understand the workings of the component nor have any interest into it (I only use browser_mod for popup cards) so the real cause has to be found and fixed by someone else.

**Comment by jeremysherriff** [comment]
Not stale.  Disabled devices are incorrectly polled for status updates, causing error spam in logs.

**Comment by EDelsman** [comment]
Same problem here, Not about to go editing pyton files to resolve this.

**Comment by gabriele-latino** [comment]
Same error for me:

`Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/entity.py:694
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 21:22:48 (227 occurrences)
Last logged: 21:36:52

[547451223536] Error handling message: Unknown error (unknown_error)
[547256844832] Error handling message: Unknown error (unknown_error)
[547451047840] Error handling message: Unknown error (unknown_error)
[546696176112] Error handling message: Unknown error (unknown_error)
[546964392352] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 107, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
    self.updated()
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 694, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'`
