### ISSUE TITLE
Can't Clean Devices

### ISSUE THREAD

**Issue by wanagel** [thomasloven/hass-browser_mod#280]
My Home Assistant version: 2021.12.1

**What I am doing:**

High-level, what I'm trying to accomplish is to get rid of around 40 devices that have built up over time. 

I tried adding 

```yaml
devices:
   XXXXXXXX-XXXXXXXX: // I obfuscated these, real config has real ids
     name: living_room_tablet
     disable:
       - light
   XXXXXXXX-XXXXXXXX:
     name: laptop_safari
   XXXXXXXX-XXXXXXXX:
     name: laptop_ha_app
   XXXXXXXX-XXXXXXXX:
     name: office_tablet
   XXXXXXXX-XXXXXXXX:
     name: iphone
disable:
  - all
```

But the devices are still there. So, next I tried running browser_mod.clean_devices, and that is resulting in "unknown error".

I have tried restarting Home Assistant multiple times.

**What I expected to happen:**

I want unused devices to go away so that I end up with only the small set of devices I've specifically configured aliases for.

**What happened instead:**

In the browser, when I use the HA UI for calling the service, it pops up an error saying the call failed with "unknown error". 

**Minimal** steps to reproduce:

Call service (from the HA UI Developer Tools) with:

```yaml
service: browser_mod.clean_devices
data: {}
```

**Error messages from the logs:**

```
2021-12-23 10:02:00 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2021-12-23 10:02:00 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2021-12-23 10:02:00 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object has no attribute 'state'
Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/Users/homeassistant/.homeassistant/custom_components/browser_mod/service.py", line 54, in call_service
    await async_clean_devices(hass, service_call.data)
  File "/Users/homeassistant/.homeassistant/custom_components/browser_mod/service.py", line 86, in async_clean_devices
    if entity.state != STATE_UNAVAILABLE:
AttributeError: 'NoneType' object has no attribute 'state'
2021-12-23 10:02:00 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [4858531792] Error handling message: Unknown error
Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/commands.py", line 527, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 1259, in async_run
    await asyncio.shield(run.async_run())
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 363, in async_run
    await self._async_step(log_exceptions=False)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/Users/homeassistant/.homeassistant/custom_components/browser_mod/service.py", line 54, in call_service
    await async_clean_devices(hass, service_call.data)
  File "/Users/homeassistant/.homeassistant/custom_components/browser_mod/service.py", line 86, in async_clean_devices
    if entity.state != STATE_UNAVAILABLE:
AttributeError: 'NoneType' object has no attribute 'state'
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by maretodoric** [comment]
Check this out. I'm not a developer of this integration but I'm debugging this as I'm hitting the same issue as you did and found this...

You have a browser_mod device or entities of that device disabled. Enable them all

Go to Integrations and open all Browser Mod devices.
Click on one of them and make sure it's enabled
After that, make sure all of it's entities are enabled too.
Repeat for all others and then try running the clean_devices service again.

This worked for me just fine!
I'm figuring out if there is a safe approach to remove them even if the device is disabled, unless developer figures it out sooner, as I'm not very familiar with home assistant development.

**Comment by maretodoric** [comment]
Just created pull request #287 with a fix for this.
This may not be the best way to fix it since as i mentioned, I'm not very good with Home Assistant core development but this will give developer of this mod a good pointer of how to proceed.

**Comment by KixMan28** [comment]
@maretodoric Than you for the hint on how to remove the unused/unavailable devices. I was struggling with this  since a while, but now finally all went away

**Comment by maretodoric** [comment]
Very glad i could help!

**Comment by felipecrs** [comment]
https://www.home-assistant.io/blog/2022/02/02/release-20222/#improved-handling-of-device-tracker-entities

I think we could also do something like what was done in the above. All browsers could appear disabled by default, unless the user explicitly enables it, either via YAML or the UI.
