### ISSUE TITLE
Error during setup of component browser_mod 

### ISSUE THREAD

**Issue by yacinegithub** [thomasloven/hass-browser_mod#291]
My Home Assistant version: 2021.12.10
What I am doing:
restarting HA

What I expected to happen:
nothing

What happened instead:
browser_mod loading error

Minimal steps to reproduce:
Installed through HACS, worked before, suddenly notice it Is not working and saw the error in the logs
tried to uninstall and reinstall the plugin - no help.

Error messages from the browser console:

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/browser_mod/__init__.py:40
Integration: browser_mod (documentation)
First occurred: 11:04:08 (1 occurrences)
Last logged: 11:04:08

Error during setup of component browser_mod
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/browser_mod/__init__.py", line 40, in async_setup
    name = config[DOMAIN][CONFIG_DEVICES][d].get("name", None)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by yacinegithub** [comment]
solved by reinstalling browser mod
