### ISSUE TITLE
Popup not appears

### ISSUE THREAD

**Issue by spacyt** [thomasloven/hass-browser_mod#325]
Hello,

after update to ->

Home Assistant Core 2022.5.2
Home Assistant Supervisor 2022.05.0
Home Assistant OS 7.6

browser_mod not working like accepted.
Popups not appering. 

**What I expected to happen:**

**What happened instead:**

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
 File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
  File "/config/custom_components/browser_mod/connection.py", line 101, in update
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
  File "/config/custom_components/browser_mod/media_player.py", line 51, in updated
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
  File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
  File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
  File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
  File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
  File "/config/custom_components/browser_mod/connection.py", line 101, in update
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
  File "/config/custom_components/browser_mod/media_player.py", line 51, in updated```


devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
    self.updated()
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 694, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
2022-05-09 20:55:29 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547158377760] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 107, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
    self.updated()
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 694, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
2022-05-09 20:55:29 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547158377760] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 107, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
    self.updated()
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 694, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
2022-05-09 20:55:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547158377760] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 107, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
    self.updated()
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 694, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
2022-05-09 20:55:33 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547158377760] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 107, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
    self.updated()
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 694, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
2022-05-09 20:55:33 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547158377760] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 107, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
    self.updated()
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 694, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
2022-05-09 20:55:43 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547158377760] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 107, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
    self.updated()
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 694, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ ] Have made sure I am using the latest version of the plugin.

- [ ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by maxxer** [comment]
Are you in HTTPS? It started working to me when I enabled secure connection
