### ISSUE TITLE
BM beta: Failed to setup - ResourceYAMLCollection' object has no attribute 'async_create_item

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/hass-browser_mod#347]
My Home Assistant version:

Home Assistant 2022.8.0
Supervisor 2022.08.0
Operating System 8.4
Frontend 20220802.0 - latest

**What I am doing:**
restarted after having installed and successfully added my browsers, which were visible in the Integration panel

**What I expected to happen:**
Keep this, and correctly initialize BM at startup

**What happened instead:**

<img width="299" alt="Schermafbeelding 2022-08-04 om 11 46 39" src="https://user-images.githubusercontent.com/33354141/182817548-5ee2d5dd-af0d-4fce-aa61-8d07914f8e7d.png">

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/browser_mod/mod_view.py:56 
Integration: Browser mod (documentation) 
First occurred: 11:37:26 (1 occurrences) 
Last logged: 11:37:26

Error setting up entry Browser Mod for browser_mod
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/browser_mod/__init__.py", line 34, in async_setup_entry
    await async_setup_view(hass)
  File "/config/custom_components/browser_mod/mod_view.py", line 56, in async_setup_view
    await resources.async_create_item(
AttributeError: 'ResourceYAMLCollection' object has no attribute 'async_create_item'


```

even though the Side panel menu shows all browsers::

<img width="671" alt="Schermafbeelding 2022-08-04 om 11 47 34" src="https://user-images.githubusercontent.com/33354141/182817737-2cc6e423-1983-4b55-aa9a-2521e2775b1b.png">

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X ] Have made sure I am using the latest version of the plugin.

- [ X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Mariusthvdb** [comment]
Update:

downloaded the updated mod_view.py file and restarted: same issue.
 But now, All errors on:
```
Logger: homeassistant.components.light
Source: helpers/entity_platform.py:652 
Integration: Light (documentation, issues) 
First occurred: 12:17:42 (1 occurrences) 
Last logged: 12:17:42

Platform browser_mod does not generate unique IDs. ID 281f6337-ce4e6afb-Screen already exists - ignoring light.hvbmbpro16_safari_nc_screen
```

for all my browser id's.

Figured BM should be re-installed a fresh, so deleted the integration (in the panel, forgot to check the side panel)

Then re-added the BM integration via the config flow, which leads directly to:

<img width="284" alt="Schermafbeelding 2022-08-04 om 12 33 39" src="https://user-images.githubusercontent.com/33354141/182826646-da002ab8-680c-41f8-9989-db4a77d60a8b.png">

and, checking the log reveals:
```
This error originated from a custom integration.

Logger: custom_components.browser_mod.config_flow
Source: custom_components/browser_mod/config_flow.py:17 
Integration: Browser mod (documentation) 
First occurred: 12:31:12 (1 occurrences) 
Last logged: 12:31:12

Running async_create_entry
```

 and 

```
Logger: homeassistant.config_entries
Source: components/frontend/__init__.py:279 
First occurred: 12:31:12 (1 occurrences) 
Last logged: 12:31:12

Error setting up entry Browser Mod for browser_mod
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/browser_mod/__init__.py", line 34, in async_setup_entry
    await async_setup_view(hass)
  File "/config/custom_components/browser_mod/mod_view.py", line 24, in async_setup_view
    hass.components.frontend.async_register_built_in_panel(
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 279, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel browser-mod

```

now what to do.....

**Comment by Mariusthvdb** [comment]
after applying the last edits/updates, this is resolved, so closing ;-)
