### ISSUE TITLE
Toast notifications not working in 2.1.0

### ISSUE THREAD

**Issue by shogun168** [thomasloven/hass-browser_mod#389]
My Home Assistant version: 0.XX.X

**What I am doing:**
Adding a browser mod notification to a script

**What I expected to happen:**
A toast notification to appear when the action is run

**What happened instead:**
No toast notification appears

**Minimal** steps to reproduce:
As described above using the code below

```yaml
# The least amount of code or steps possible to reproduce my error

service: browser_mod.notification
data:
  message: Test


# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

"notify":"init_tab"}
:8123/local/card-mod.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
card-mod.js:5 CARD-MOD 3.1.5 IS INSTALLED
:8123/config/lovelace/resources:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://homeassistant.local:8123/local/card-mod.js
browser_mod.js:373 BROWSER_MOD 2.1.0 IS INSTALLED    BrowserID: CarnelianHellFireBrowser
hass-hue-icons.js:1978  HASS-HUE-ICONS  Version 1.2.43 
o486460.ingest.sentry.io/api/5543748/envelope/?sentry_key=d7d41ba9c12d4f7cb91a314fef9dea09&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.10.0:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
layout-card.js?hacstag=156434866242:228 LAYOUT-CARD 2.4.2 IS INSTALLED
kiosk-mode.js?hacstag=497319128173:64 ≡ kiosk-mode            ⋮ 
version 1.7.3            
directive.js:6   BUTTON-TEXT-CARD   v0.6.0    
custom-icons.js?hacstag=491465538035:273   Custom-icons    Version 0.3.5 22020722
collapsable-cards.js?hacstag=364978303050:1 collapsable-cardsVersion: 0.0.1
multiple-entity-row.js?hacstag=178921037441:1  MULTIPLE-ENTITY-ROW  4.4.1 
utils.ts:1  BATTERY-STATE-CARD  2.1.1
button-card.js?hacstag=146194325342:425   BUTTON-CARD   Version 3.4.2 
mini-graph-card-bundle.js?hacstag=1512800620110:1  MINI-GRAPH-CARD  0.11.0 
timer-bar-card.js?hacstag=376904517120:170  TIMER-BAR-CARD  Version 1.20.0 
hourly-weather.js?hacstag=499270202431:259   HOURLY-WEATHER-CARD   Version 4.3.1    
mushroom.js?hacstag=444350375213:2823 🍄 Mushroom 🍄 - 2.1.3
card-tools.js?hacstag=16140332811:90 CARD-TOOLS 2.1.2 IS INSTALLED  DeviceID: afa4f928-00bf6304
hass-hue-icons.js?hacstag=3844345221243:1978  HASS-HUE-ICONS  Version 1.2.43 
text-divider-row.js?hacstag=179788256141:187   TEXT-DIVIDER-ROW    Version 1.4.1     
minimalistic-area-card.js?hacstag=489457357106:40   Minimalistic Area Card   1.0.6 
stack-in-card.js?hacstag=248954055020:200  STACK-IN-CARD    Version 0.2.0   
fold-entity-row.js?hacstag=150781994220:78 FOLD-ENTITY-ROW 2.2.0 IS INSTALLED 
uptime-card.js?hacstag=3505098670111:451  uptime-card    0.11.1    
state-switch.js?hacstag=158756598195:139 STATE-SWITCH 1.9.5 IS INSTALLED 
weather-radar-card.js?hacstag=487680971206:1291   WEATHER-RADAR-CARD   Version 2.0.5    
hui-error-badge.ts:22 TypeError: Cannot read properties of null (reading 'location_name')
    at y.generateDashboard (02f69f4f.js:1:9744)
    at o (hui-error-badge.ts:22:1)
    at async r.value (ha-panel-lovelace.ts:144:1)
    at async ue (browser_mod.js:66:1982)
o @ hui-error-badge.ts:22
sidebar-card.js?hacstag=2418255740184:661   SIDEBAR-CARD              Version: 0.1.8.4        
:8123/config/lovelace/resources:1 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "sidebar-card" has already been used with this registry
DevTools failed to load source map: Could not load content for chrome-extension://lggdbpblkekjjbobadliahffoaobaknh/static/js/content.js.map: System error: net::ERR_FILE_NOT_FOUND

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by shogun168** [comment]
Not sure what changed but seems to be working now. Closing.
