### ISSUE TITLE
Frontend become unavailable after refreshing browser

### ISSUE THREAD

**Issue by AndyVRD** [thomasloven/hass-browser_mod#418]
My Home Assistant version: 2022.9

**What I am doing:**
Started from scratch installing browser_mod V2, double checked in chrome dev console and nothing from v1 is loaded. After both restarts (first one after installating hacs integration and second one after installing the integration) soon as i hit F5 to refresh the browser my frontend becomes unavailable. First time it shows the home assistant logo with 60sec counting timer, second refresh it only shows the home assistant logo without the counting part under it.

**What I expected to happen:**
My frontend keeps working...

**What happened instead:**
Frontend becomes unavailable. I tested this in both chrome and firefox and also with incognito mode. Soon as i delete the cache of the browsers and login my frontend is loading until i hit F5...

**Minimal** steps to reproduce:
I think it's hard because i don't see any other messages about the problem i have.

**Error messages from the browser console:**

```
BROWSER_MOD 2.0.0 IS INSTALLED    BrowserID: eff10211-d81a2532
typography.js:181 Uncaught TypeError: Illegal constructor (custom element class must be registered with global customElements registry to be newable)
    at new window.HTMLElement (typography.js:181:1)
    at new b (styles.ts:370:1)
    at new w (styles.ts:370:1)
    at new F (styles.ts:370:1)
    at new <anonymous> (styles.ts:370:1)
    at new <anonymous> (styles.ts:370:1)
    at new <anonymous> (styles.ts:370:1)
    at new <anonymous> (styles.ts:370:1)
    at new <anonymous> (styles.ts:370:1)
    at new <anonymous> (styles.ts:370:1)

***(typography.js:181:1) referencing to this part:***

typography.js

  </style>
</custom-style>`;
template.setAttribute('style', 'display: none;');
document.head.appendChild(template.content);
```

---
**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by AndyVRD** [comment]
Fixed.
