### ISSUE TITLE
Cannot update to V2 - ValueError: Overwriting panel browser-mod

### ISSUE THREAD

**Issue by craigmcewen** [thomasloven/hass-browser_mod#470]
Hi, 

Been attemopting to upgrade to the new version for over a week now and I am having no success. 

I have uninstalled - restarted - cleared cache - left it a few days - come back to install - restarted - clear cache and signed in using other browser. 

I keep getting an error after the integration is added into HA, it is persistent through reboots,

Error: 

2022-10-08 19:51:06.081 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Browser Mod for browser_mod
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/browser_mod/__init__.py", line 34, in async_setup_entry
await async_setup_view(hass)
File "/config/custom_components/browser_mod/mod_view.py", line 24, in async_setup_view
hass.components.frontend.async_register_built_in_panel(
File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 279, in async_register_built_in_panel
raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel browser-mod

Please let me know what I am doing wrong

**Comment by luismalves** [comment]
Also having the exact same issue... Have clean installation already.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/browser_mod/__init__.py", line 34, in async_setup_entry
    await async_setup_view(hass)
  File "/config/custom_components/browser_mod/mod_view.py", line 24, in async_setup_view
    hass.components.frontend.async_register_built_in_panel(
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 279, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel browser-mod
```

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/browser_mod/__init__.py", line 34, in async_setup_entry
    await async_setup_view(hass)
  File "/config/custom_components/browser_mod/mod_view.py", line 47, in async_setup_view
    if r["url"].startswith(FRONTEND_SCRIPT_URL):
KeyError: 'url'
```

**Comment by FrnchFrgg** [comment]
You may still have remnants of browser mod. Maybe some extra module url or lovelace resources trying to load part of the old browser mod, which would load a part of the new browser mod at the wrong time or twice ?

**Comment by thomasloven** [comment]
Looks like browser_mod is loaded twice.
Make sure it's fully removed from any yaml configuration.
