### ISSUE TITLE
Background of popup-card doesn't match the rest of the theme

### ISSUE THREAD

**Issue by MasterDevwi** [thomasloven/hass-browser_mod#559]
My Home Assistant version: 2023.3.6

**What I am doing:**
When using a theme, the background of the custom:popup-card doesn't match the background of the rest of the Home Assistant info cards. It either doesn't have transparency at all or it is _too_ transparent. At best, this makes popup-cards look different than the rest of the UI, and at worst they're much harder to read.

**What I expected to happen vs what happened:**
Here's a few examples:

**Fluent Blue theme:**
Default info card:
![image](https://user-images.githubusercontent.com/5544757/228081255-2d3e6853-3fbc-4e6e-aa1b-64275337050d.png)

custom:popup-card:
![image](https://user-images.githubusercontent.com/5544757/228081133-aa267efc-8009-476f-bef6-0ca2ca60e7bf.png)

**iOS Dark Mode Blue-Red:**
Default info card:
![image](https://user-images.githubusercontent.com/5544757/228081608-2595efd5-cee6-4479-924b-b805a1f51adf.png)

custom:popup-card:
![image](https://user-images.githubusercontent.com/5544757/228081703-eb24ae18-02b5-46ce-8d5d-b7960e1203f9.png)

**Minimal** steps to reproduce:
1. Install a browser theme like [iOS Themes - Dark Mode and Light Mode](https://github.com/basnijholt/lovelace-ios-themes) or [Metrology - Metro + Fluent + Windows Themes](https://github.com/Madelena/Metrology-for-Hass) (although I've seen this issue with other themes too).
2. Enable a theme like ios-dark-mode-blue-red or Fluent Blue.
3. Go to lovelace and click on an entity to open a default Home Assistant info card
4. Now click on an entity to open a custom:popup-card
5. Compare the background of the two cards and note how different they are

**Error messages from the browser console:**
```
card-mod.js?hacstag=190927524320:5 CARD-MOD 3.2.0 IS INSTALLED
card-mod.js?hacstag=190927524320:5 You may not be getting optimal performance out of card-mod.
See https://github.com/thomasloven/lovelace-card-mod#performance-improvements
browser_mod.js:407 BROWSER_MOD 2.2.0 IS INSTALLED    BrowserID: 2761b8d7-a0bc912f
card-mod.js?hacstag=190927524320:1  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'themes')
    at card-mod.js?hacstag=190927524320:1:21544
    at card-mod.js?hacstag=190927524320:1:21715
    at set styles [as styles] (card-mod.js?hacstag=190927524320:1:21761)
    at card-mod.js?hacstag=190927524320:1:19434
(anonymous) @ card-mod.js?hacstag=190927524320:1
(anonymous) @ card-mod.js?hacstag=190927524320:1
set styles @ card-mod.js?hacstag=190927524320:1
(anonymous) @ card-mod.js?hacstag=190927524320:1
await in (anonymous) (async)
set styles @ card-mod.js?hacstag=190927524320:1
(anonymous) @ card-mod.js?hacstag=190927524320:1
auto-entities.js?hacstag=1677445841121:172 AUTO-ENTITIES 1.12.1 IS INSTALLED
state-switch.js?hacstag=158756598195:139 STATE-SWITCH 1.9.5 IS INSTALLED 
slider-entity-row.js?hacstag=1448997001730:82 SLIDER-ENTITY-ROW 17.3.0 IS INSTALLED 
6a1bc7e3.js:2 
        
        
        GET https://url.ui.nabu.casa/local/style.css net::ERR_ABORTED 404 (Not Found)
(anonymous) @ 6a1bc7e3.js:2
r @ 6a1bc7e3.js:2
o @ 6a1bc7e3.js:2
(anonymous) @ 6a1bc7e3.js:2
s @ 6a1bc7e3.js:2
(anonymous) @ 6a1bc7e3.js:2
Promise.then (async)
value @ 6a1bc7e3.js:2
pe @ browser_mod.js:66
await in pe (async)
(anonymous) @ browser_mod.js:253
(anonymous) @ browser_mod.js:66
Re @ browser_mod.js:407
(anonymous) @ browser_mod.js:407
6a1bc7e3.js:2 
        
        
        GET https://url.ui.nabu.casa/local/vacuum-card.js net::ERR_ABORTED 404 (Not Found)
(anonymous) @ 6a1bc7e3.js:2
r @ 6a1bc7e3.js:2
s @ 6a1bc7e3.js:2
(anonymous) @ 6a1bc7e3.js:2
s @ 6a1bc7e3.js:2
(anonymous) @ 6a1bc7e3.js:2
Promise.then (async)
value @ 6a1bc7e3.js:2
pe @ browser_mod.js:66
await in pe (async)
(anonymous) @ browser_mod.js:253
(anonymous) @ browser_mod.js:66
Re @ browser_mod.js:407
(anonymous) @ browser_mod.js:407
template-entity-row.js?hacstag=231674882131:48 TEMPLATE-ENTITY-ROW 1.3.1 IS INSTALLED 
ha-app-layout.js:101  TypeError: Cannot read properties of null (reading 'location_name')
    at a.generateDashboard (6d296ee5.js:1:18737)
    at o (ha-app-layout.js:101:1)
    at async r.value (6a1bc7e3.js:2:49003)
    at async pe (browser_mod.js:66:1982)
o @ ha-app-layout.js:101
await in o (async)
s @ ha-app-layout.js:101
value @ 6a1bc7e3.js:2
await in value (async)
pe @ browser_mod.js:66
await in pe (async)
(anonymous) @ browser_mod.js:253
(anonymous) @ browser_mod.js:66
Re @ browser_mod.js:407
(anonymous) @ browser_mod.js:407
layout-card.js?hacstag=156434866244:228 LAYOUT-CARD 2.4.4 IS INSTALLED
vertical-stack-in-card.js?hacstag=142051833044:1 vertical-stack-in-cardVersion: 0.4.4
utils.ts:1  BATTERY-STATE-CARD  2.1.1
fold-entity-row.js?hacstag=150781994220:78 FOLD-ENTITY-ROW 2.2.0 IS INSTALLED 
badge-card.js?hacstag=2814536085672:6 BADGE-CARD 1.0.1 IS INSTALLED 
numberbox-card.js?hacstag=30496791847:3 NUMBERBOX_CARD 4.7
default-dashboard.js?hacstag=567030726111:1   DEFAULT-DASHBOARD   Version 1.0.10   
swipe-navigation.js?hacstag=5017254791110:1 ↔️ Swipe navigation ↔️ - v1.11.0
apexcharts-card.js?hacstag=331701152202:835  APEXCHARTS-CARD  v2.0.2 
mini-graph-card-bundle.js?hacstag=1512800620110:1  MINI-GRAPH-CARD  0.11.0 
vacuum-card.js?hacstag=261291295263:4  VACUUM-CARD  2.6.2 
button-card.js?hacstag=146194325342:425   BUTTON-CARD   Version 3.4.2 
6a1bc7e3.js:2  Uncaught (in promise) https://url.ui.nabu.casa/local/style.css
n.onerror @ 6a1bc7e3.js:2
error (async)
(anonymous) @ 6a1bc7e3.js:2
r @ 6a1bc7e3.js:2
o @ 6a1bc7e3.js:2
(anonymous) @ 6a1bc7e3.js:2
s @ 6a1bc7e3.js:2
(anonymous) @ 6a1bc7e3.js:2
Promise.then (async)
value @ 6a1bc7e3.js:2
pe @ browser_mod.js:66
await in pe (async)
(anonymous) @ browser_mod.js:253
(anonymous) @ browser_mod.js:66
Re @ browser_mod.js:407
(anonymous) @ browser_mod.js:407
index.js:9 harmony-remote-card v1.4.3
6a1bc7e3.js:2  Uncaught (in promise) https://url.ui.nabu.casa/local/vacuum-card.js
n.onerror @ 6a1bc7e3.js:2
error (async)
(anonymous) @ 6a1bc7e3.js:2
r @ 6a1bc7e3.js:2
s @ 6a1bc7e3.js:2
(anonymous) @ 6a1bc7e3.js:2
s @ 6a1bc7e3.js:2
(anonymous) @ 6a1bc7e3.js:2
Promise.then (async)
value @ 6a1bc7e3.js:2
pe @ browser_mod.js:66
await in pe (async)
(anonymous) @ browser_mod.js:253
(anonymous) @ browser_mod.js:66
Re @ browser_mod.js:407
(anonymous) @ browser_mod.js:407
my-cards.js?hacstag=399108901102:186   ---- MY-SLIDER ----   Version 3.0.3    
my-cards.js?hacstag=399108901102:356   ---- MY-SLIDER-V2 ----   Version 3.0.3    
my-cards.js?hacstag=399108901102:356 HELLO FROM SLIDER-V2
my-cards.js?hacstag=399108901102:375   ---- MY-BUTTON ----   Version 1.0.0    
my-cards.js?hacstag=399108901102:436   ---- MY-CARDS ----   Version 2.0.1    
config-template-card.js?hacstag=172177543136:329  The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
(anonymous) @ config-template-card.js?hacstag=172177543136:329
config-template-card.js?hacstag=172177543136:735   CONFIG-TEMPLATE-CARD    Version 1.3.6         
lovelace-card-templater.js?hacstag=1843331630017:144   CARD-TEMPLATER   Version 0.0.9  
floorplan.js?hacstag=1883234941035:31  The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
parcelRequire.naA1.@lit/reactive-element @ floorplan.js?hacstag=1883234941035:31
f @ floorplan.js?hacstag=1883234941035:2
p @ floorplan.js?hacstag=1883234941035:2
parcelRequire.a9JD.lit-element @ floorplan.js?hacstag=1883234941035:170
f @ floorplan.js?hacstag=1883234941035:2
p @ floorplan.js?hacstag=1883234941035:2
parcelRequire.QCba../components/floorplan-card/floorplan-card @ floorplan.js?hacstag=1883234941035:231
f @ floorplan.js?hacstag=1883234941035:2
parcelRequire.jMeY @ floorplan.js?hacstag=1883234941035:2
(anonymous) @ floorplan.js?hacstag=1883234941035:2
floorplan.js?hacstag=1883234941035:87 Floorplan for Home Assistant (ha-floorplan)Version 1.0.35
linked-lovelace-ui.js?hacstag=559360809150:84   LINKED-LOVELACE-UI   Version 1.5.0   
mushroom.js?hacstag=444350375261:3046 🍄 Mushroom 🍄 - 2.6.1
```

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by zanix** [comment]
I [submitted a PR](https://github.com/Madelena/Metrology-for-Hass/pull/62) to fix this for [Metrology - Metro + Fluent + Windows Themes](https://github.com/Madelena/Metrology-for-Hass) and it was merged a few days ago. There hasn't been a new release as of yet.
That said, it would be nice if it was fixed on Browser Mod itself

**Comment by MasterDevwi** [comment]
Thank you so much! Looking forward to testing it once it's released.

**Comment by MasterDevwi** [comment]
This is still not working in other themes. It sounds like it’s an issue in Browser Mod?
