### ISSUE TITLE
Websocket API issue with Browser Mod?

### ISSUE THREAD

**Issue by ThatTallGuy21** [thomasloven/hass-browser_mod#584]
My Home Assistant version: 2023.5.4

I'm seeing the following error in my log when I first start up HA. 

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/browser_mod/browser.py:65
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:44:06 AM (1 occurrences)
Last logged: 10:44:06 AM

[140010137337088] Error handling message: Unknown error (unknown_error) Admin from 127.0.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/browser_mod/connection.py", line 143, in handle_update
    dev = getBrowser(hass, browserID)
  File "/config/custom_components/browser_mod/browser.py", line 198, in getBrowser
    browsers[browserID] = BrowserModBrowser(hass, browserID)
  File "/config/custom_components/browser_mod/browser.py", line 42, in __init__
    self.update_entities(hass)
  File "/config/custom_components/browser_mod/browser.py", line 71, in update_entities
    _assert_browser_sensor("sensor", "path", "Browser path", icon="mdi:web")
  File "/config/custom_components/browser_mod/browser.py", line 65, in _assert_browser_sensor
    adder = hass.data[DOMAIN][DATA_ADDERS][type]
KeyError: 'sensor'

**Comment by mdeweerd** [comment]
On HA 2023.6.1

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/browser_mod/connection.py", line 143, in handle_update
    dev = getBrowser(hass, browserID)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/browser_mod/browser.py", line 198, in getBrowser
    browsers[browserID] = BrowserModBrowser(hass, browserID)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/browser_mod/browser.py", line 42, in __init__
    self.update_entities(hass)
  File "/config/custom_components/browser_mod/browser.py", line 71, in update_entities
    _assert_browser_sensor("sensor", "path", "Browser path", icon="mdi:web")
  File "/config/custom_components/browser_mod/browser.py", line 65, in _assert_browser_sensor
    adder = hass.data[DOMAIN][DATA_ADDERS][type]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'sensor'
```

**Comment by Kaptensanders** [comment]
Same here, on 2023.8.3

  File "/config/custom_components/browser_mod/browser.py", line 65, in _assert_browser_sensor
    adder = hass.data[DOMAIN][DATA_ADDERS][type]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'sensor'

**Comment by stonegray** [comment]
Persists in 2023.10.5

```
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/browser_mod/connection.py", line 143, in handle_update
    dev = getBrowser(hass, browserID)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/browser_mod/browser.py", line 198, in getBrowser
    browsers[browserID] = BrowserModBrowser(hass, browserID)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/browser_mod/browser.py", line 42, in __init__
    self.update_entities(hass)
  File "/config/custom_components/browser_mod/browser.py", line 71, in update_entities
    _assert_browser_sensor("sensor", "path", "Browser path", icon="mdi:web")
  File "/config/custom_components/browser_mod/browser.py", line 65, in _assert_browser_sensor
    adder = hass.data[DOMAIN][DATA_ADDERS][type]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'sensor'
```

**Comment by ippo112** [comment]
same in the 2023.11.3,
please some help to resolve.
thnaks

**Comment by cgbaker** [comment]
Persists with `2024.1.5` and Browser Mod `2.3.0`
