### ISSUE TITLE
Error after upgrade to HA 2023.11.3

### ISSUE THREAD

**Issue by ippo112** [thomasloven/hass-browser_mod#658]
My Home Assistant version: 2023.11.3

**What I am doing:**
when I restrt HA some errors on debug ...

**Error messages from the browser console:**

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/browser_mod/browser.py:65
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 07:25:04 (21 occurrences)
Last logged: 07:25:05

[140147459870784] Error handling message: Unknown error (unknown_error) "pincopallo"from 192.168.1.xx (Mozilla/5.0 (Linux; Android 11; HiPadPro Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.163 Safari/537.36)
[140147452535232] Error handling message: Unknown error (unknown_error) "picopallo" from 192.168.1.xx (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/browser_mod/connection.py", line 61, in handle_connect
    dev = getBrowser(hass, browserID)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/browser_mod/browser.py", line 198, in getBrowser
    browsers[browserID] = BrowserModBrowser(hass, browserID)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/browser_mod/browser.py", line 42, in __init__
    self.update_entities(hass)
  File "/config/custom_components/browser_mod/browser.py", line 71, in update_entities
    _assert_browser_sensor("sensor", "path", "Browser path", icon="mdi:web")
  File "/config/custom_components/browser_mod/browser.py", line 65, in _assert_browser_sensor
    adder = hass.data[DOMAIN][DATA_ADDERS][type]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'sensor'

```
the integration seems to work correctly, but when starting "HA" the above error is present and appears at least 20 times in the log file  
---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X ] Have made sure I am using the latest version of the plugin.

- [X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by darrynlowe** [comment]
Getting the same thing here. I've got several machines running browser_mod in a kiosk configurtaion, and I get repeated messages for each of them. 

HA version: 2024.1.0

```
2024-01-04 10:22:57.984 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140370829984448] Error handling message: Unknown error (unknown_error) Kiosk-Vert from IPV6_ADDRESS_REDACTED (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/browser_mod/connection.py", line 143, in handle_update
    dev = getBrowser(hass, browserID)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/browser_mod/browser.py", line 198, in getBrowser
    browsers[browserID] = BrowserModBrowser(hass, browserID)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/browser_mod/browser.py", line 42, in __init__
    self.update_entities(hass)
  File "/config/custom_components/browser_mod/browser.py", line 71, in update_entities
    _assert_browser_sensor("sensor", "path", "Browser path", icon="mdi:web")
  File "/config/custom_components/browser_mod/browser.py", line 65, in _assert_browser_sensor
    adder = hass.data[DOMAIN][DATA_ADDERS][type]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'sensor'

```
