### ISSUE TITLE
All Registered Browsers Unavailable After Install of 2024.6.2

### ISSUE THREAD

**Issue by clearwave1** [thomasloven/hass-browser_mod#712]
My Home Assistant version: 2024.6.2

**What I am doing:**
I previously had a navigate automation working fine that changed a view in multiple tablets.

**What I expected to happen:**
I expected the view to change.

**What happened instead:**
No change in the targeted browsers.

**Minimal** steps to reproduce:
I noticed in the Browser Mod settings (from the left menu) that all of the registered browsers are now showing unavailable.

I have tried another restart and have tried waking the browsers and even going to the Browser Mod settings page on each browser but they think they are registered.

I have tried calling the service from the Developer Tools on just one browser. The service call completes successfully but nothing happens. The logs are below.

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```

// Select everything from the browser console and copy it

// Paste it here
```
card-mod.js?hacstag=190927524343:1 CARD-MOD 3.4.3 IS INSTALLED
browser_mod.js:385 BROWSER_MOD 2.3.0 IS INSTALLED    BrowserID: don-tablet
check-button-card.js?hacstag=164022050130:1 CHECK-BUTTON-CARDVersion: 1.3.0
fold-entity-row.js?hacstag=150781994220:78 FOLD-ENTITY-ROW 2.2.0 IS INSTALLED 
card-tools.js?hacstag=16140332811:90 CARD-TOOLS 2.1.2 IS INSTALLED  DeviceID: 880ac605-90d404d4
numberbox-card.js?hacstag=304967918417:3 NUMBERBOX_CARD 4.17
auto-entities.js?hacstag=1677445841130:172 AUTO-ENTITIES 1.13.0 IS INSTALLED
multiple-entity-row.js?hacstag=178921037451:1  MULTIPLE-ENTITY-ROW  4.5.1 
template-entity-row.js?hacstag=231674882141:1 TEMPLATE-ENTITY-ROW 1.4.1 IS INSTALLED 
config-template-card.js?hacstag=172177543136:329 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
(anonymous) @ config-template-card.js?hacstag=172177543136:329
config-template-card.js?hacstag=172177543136:735   CONFIG-TEMPLATE-CARD    Version 1.3.6         
simple-thermostat.js?hacstag=158654878250:292 simple-thermostat: 2.5.0
layout-card.js?hacstag=156434866245:228 LAYOUT-CARD 2.4.5 IS INSTALLED
button-card.js?hacstag=146194325412:426   BUTTON-CARD   Version 4.1.2 
logbook-card.js?hacstag=216008446255:457  LOGBOOK-CARD  2.5.5 
stack-in-card.js?hacstag=248954055020:200  STACK-IN-CARD    Version 0.2.0   
lovelace-home-feed-card.js?hacstag=174016256065:243   HOME-FEED-CARD   Version 0.6.4    
lovelace-card-templater.js?hacstag=1843331630017:144   CARD-TEMPLATER   Version 0.0.9  
mushroom.js?hacstag=444350375362:3130 🍄 Mushroom 🍄 - 3.6.2
card-555679fd.js:507  FRIGATE-HASS-CARD  Version 5.2.0 
connection.js:26 Received event for unknown subscription 54. Unsubscribing.
(anonymous) @ connection.js:26
Show 1 more frame
Show less
gallery-card.js?hacstag=284283867351:966 GALLERY-CARD 3.5.1 IS INSTALLED
ha-data-table.ts:390 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'localize')
    at i.value (ha-data-table.ts:390:33)
    at i.update (lit-element.ts:160:24)
    at i.performUpdate (reactive-element.ts:1329:14)
    at i.scheduleUpdate (reactive-element.ts:1261:17)
    at i._$Ej (reactive-element.ts:1233:25)
ha-data-table.ts:390 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'localize')
    at i.value (ha-data-table.ts:390:33)
    at i.update (lit-element.ts:160:24)
    at i.performUpdate (reactive-element.ts:1329:14)
    at i.scheduleUpdate (reactive-element.ts:1261:17)
    at i._$Ej (reactive-element.ts:1233:25)
browser_mod.js:66 Uncaught (in promise) 3

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by clearwave1** [comment]
I was able to get this to work again by unregistering and re-registering each browser again.

**Comment by Loic691** [comment]
Hi
I have the same issue.
The browser mod menu in the left panel are not displayed.
I tried to reinstall from HACS Brower mod and restart HA. No effect.
So I don't show the browser mod Menu and all my browser entity are not present...
