### ISSUE TITLE
Browser_mod side panel not loading on HA 2025.1

### ISSUE THREAD

**Issue by hmmbob** [thomasloven/hass-browser_mod#770]
My Home Assistant version: 2025.1.0b0

**What I am doing:**
just using HA

**What I expected to happen:**
Browser-mod side panel to be usable

**What happened instead:**
It's a blank screen with an error in the console

**Minimal** steps to reproduce:
Upgrade to HA 2025.1.*

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```
n/a

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it
Uncaught (in promise) TypeError: document.createElement(...).getRoutes is not a function
    at $e (browser_mod.js:66:1675)
$e @ browser_mod.js:66
await in $e
(anonymous) @ browser_mod.js:231
(anonymous) @ browser_mod.js:66
Ke @ browser_mod.js:385
(anonymous) @ browser_mod.js:385

browser_mod_panel.js:263 Uncaught (in promise) TypeError: document.createElement(...).getRoutes is not a function
    at browser_mod_panel.js:263:477
(anonymous) @ browser_mod_panel.js:263
await in (anonymous)
(anonymous) @ browser_mod_panel.js:263Understand this errorAI

browser_mod_panel.js:439 Uncaught (in promise) TypeError: document.createElement(...).getRoutes is not a function
    at browser_mod_panel.js:439:373
// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Happy-Cadaver** [comment]
Can confirm same error.

**Comment by jleach87** [comment]
+1 - same here.

**Comment by jleach87** [comment]
`Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 3:24:10 PM (1 occurrences)
Last logged: 3:24:10 PM

Error setting up entry Browser Mod for browser_mod
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/browser_mod/__init__.py", line 43, in async_setup_entry
    await async_setup_view(hass)
  File "/config/custom_components/browser_mod/mod_view.py", line 35, in async_setup_view
    async_register_built_in_panel(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        hass=hass,
        ^^^^^^^^^^
    ...<10 lines>...
        },
        ^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 318, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel browser-mod`

**Comment by jleach87** [comment]
`
Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 3:24:10 PM (1 occurrences)
Last logged: 3:24:10 PM

Error setting up entry Browser Mod for browser_mod
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/browser_mod/__init__.py", line 43, in async_setup_entry
    await async_setup_view(hass)
  File "/config/custom_components/browser_mod/mod_view.py", line 35, in async_setup_view
    async_register_built_in_panel(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        hass=hass,
        ^^^^^^^^^^
    ...<10 lines>...
        },
        ^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 318, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel browser-mod
`

**Comment by jleach87** [comment]
```
Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 3:24:10 PM (1 occurrences)
Last logged: 3:24:10 PM

Error setting up entry Browser Mod for browser_mod
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/browser_mod/__init__.py", line 43, in async_setup_entry
    await async_setup_view(hass)
  File "/config/custom_components/browser_mod/mod_view.py", line 35, in async_setup_view
    async_register_built_in_panel(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        hass=hass,
        ^^^^^^^^^^
    ...<10 lines>...
        },
        ^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 318, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel browser-mod
```

**Comment by zacheryrodgers** [comment]
+1 Sames. Any luck resolving? I have tried every combo of uninstall, reinstall, clear cache, clear any .yaml configs, etc

at first I thought it might be something with pulling old incompatible config vars from the HA db on startup but I am now getting this error in my browser console


```
browser_mod.js:66 Uncaught (in promise) TypeError: document.createElement(...).getRoutes is not a function at $e (browser_mod.js:66:1675)
$e @ browser_mod.js:66
await in $e
(anonymous) @ browser_mod.js:231
(anonymous) @ browser_mod.js:66
Ke @ browser_mod.js:385
(anonymous) @ browser_mod.js:385


```

**Comment by iamandymcinnes** [comment]
I think it's been changed to "_getRoutes" now so just needs updating to match the new function name

**Comment by timmmnnn** [comment]
Can confirm ^ works :) cheers!

**Comment by zacheryrodgers** [comment]
> I think it's been changed to "_getRoutes" now so just needs updating to match the new function name
> 
> 
> 
> https://github.com/home-assistant/frontend/commit/677b3249ea85d596b310be1cee99a913bebf40fb#diff-96bcf724f5d6dc1edac61c2f37defc20b4c0ab3ca5ce9f8d50e217bd32388010
> 
> 
> 
> https://github.com/search?q=repo%3Athomasloven%2Fhass-browser_mod%20getRoutes&type=code
> 
> 
> 
> If you replace "getRoutes" with "_getRoutes" in browser_mod.js and browser_mod_panel.js, clear your cache, reload, etc it will work.

Will try once I am back to my PC. Thanks 🫶

**Comment by Happy-Cadaver** [comment]
@iamandymcinnes Thank you for this, seems to be working well. Are you going to create a PR for this?

**Comment by Happy-Cadaver** [comment]
Created a [PR for this issue](https://github.com/thomasloven/hass-browser_mod/pull/775).

**Comment by LamerTex** [comment]
> I think it's been changed to "_getRoutes" now so just needs updating to match the new function name
> 
> [home-assistant/frontend@677b324#diff-96bcf724f5d6dc1edac61c2f37defc20b4c0ab3ca5ce9f8d50e217bd32388010](https://github.com/home-assistant/frontend/commit/677b3249ea85d596b310be1cee99a913bebf40fb#diff-96bcf724f5d6dc1edac61c2f37defc20b4c0ab3ca5ce9f8d50e217bd32388010)
> 
> https://github.com/search?q=repo%3Athomasloven%2Fhass-browser_mod%20getRoutes&type=code
> 
> If you replace "getRoutes" with "_getRoutes" in browser_mod.js and browser_mod_panel.js, clear your cache, reload, etc it will work.

Sorry for bothering you, but I also have this problem. I've updated the 2 files using a file editor, as you said (and like the PR from @Happy-Cadaver ). But then I'm not sure what to do next. What does "clear your cache, reload, etc. " mean? 

I've tried rebooting HomeAssistant completely and deleting the cache (I also tried in an incognito window just to be sure), but I still have the blank page. What am I missing?

**Comment by Happy-Cadaver** [comment]
@LamerTex are you sure you saved the files after updating? I've done that myself.

My process was update and save both files, restart HA, clear browser cache through browser settings, open the Browser_mod settings page, and fully reload with ctrl+F5.

**Comment by j9brown** [comment]
Sometimes it can be difficult to clear the browser cache completely.  It can help to change the resource URL.

Go to Edit Dashboard -> Manage Resources and edit the entry for browser mod to add some arbitrary attribute to make the URL unique

e.g. /browser_mod.js?automatically-added&z=2

**Comment by brettmiller** [comment]
What finally worked for me in Chrome to clear the cache after updating the files was to go to Settings->Privacy and Security -> Delete browsing data -> select just "Cached images and files" and click "Delete data" then refresh the Browser_mod settings page.

**Comment by brettmiller** [comment]
Also of note, the pyscript integration needs to have the `Allow All Imports` option set otherwise it can't load the viewassist-select_random_image.py script. It fails at `import os`.

**Comment by arcalulu** [comment]
In case none of the steps you applied below work (this was my case even after clearing the cache):
Delete the two files located in custom_components/browser_mod/ :
 - browser_mod.js.gz
 - browser_mod_panel.js.gz
 I don't know if these two files are present for everyone (maybe through HACS), but they were the ones preventing the changes made to the ".js" files from being applied.

**Comment by LamerTex** [comment]
Thanks all for your suggestions, I confirm that the changes fix the problem, and the difficulty is to make the various apps/browsers to forget the old .js file.

This is what worked for me in the various cases:

- Android HomeAssistant app -> Andoird app settings, "Delete cache" and then it works

- Android Chrome -> Worked after a while without doing anything

- Android FullyKiosk browser -> Privacy Check, deleted everything and then it works

- PC Firefox -> worked after deleting the cache

- PC Chrome -> after trying everything, it still doesn't work. It no longer gives the same error in the Browser console, but the page is still blank... Is not a problem because I've registered the new browser that I needed it's just strange.
I will try again in the next days, for sure the problem is on the browser part and not in browser_mod since it works everywhere else.

**Comment by iamandymcinnes** [comment]
It would be good to put a cache busting strategy in, I tend to append the version on the end of assets so on each release they are reloaded, i.e. something like:

browser_mod.js?_=2025.1.1

**Comment by victoroos** [comment]
Maybe I'm jsut stupid but I edietd teh files in teh custom_components folder right?
When trying to load, whatever browser / device it doesn't work. it still loads the .getRoutes instead of the ._getRoutes

**Comment by Montreal666** [comment]
> getRoutes

for PC-Chrome: empty cache and hard reload works here (ctrl-F5)

**Comment by LamerTex** [comment]
> @LamerTex
> 
> for PC-Chrome: empty cache and hard reload works here (ctrl-F5)

Yes I think it also worked here thanks, the error with .getRoutes was fixed after a while, but there is another problem, that is beyond the scope of this discussion, which is still causing the blank page it seems.
![image](https://github.com/user-attachments/assets/88496ece-df27-4e42-a6ab-8b7931c75747)

But if I go in an incognito window or use Firefox it works correctly so it's not a problem for me.

**Comment by Pauligrinder** [comment]
Just a quick FYI: maybe it's because I'm not running the most recent version of Home-Assistant, but for me _getRoutes doesn't exist and I had to change back to getRoutes without the _ . After doing that it works.

**Comment by thomasloven** [comment]
Only the latest version of Home Assistant is ever "officially supported".
I recommend using HACS, as that would not let you install the latest version of Browser Mod unless you have at least Home Assistant 2025.01.

**Comment by Pauligrinder** [comment]
> Only the latest version of Home Assistant is ever "officially supported".
> I recommend using HACS, as that would not let you install the latest version of Browser Mod unless you have at least Home Assistant 2025.01.

Yeah, got it. I'm just not using HACS because I'm a bit old school and try to use as few external things as possible - I feel like using HACS would make it too easy to install unnecessary stuff on a whim. 

So I guess what I actually should've done, rather than revert the changes by hand, would've been to find the commit that adds those changes and checkout it, instead of the latest. But yeah, I'll probably update Home-Assistant to the latest version next week (which I guess will also force me to update Python, yikes), so then I'll update browser-mod as well...

**Comment by thomasloven** [comment]
> which I guess will also force me to update Python


While impressed; I'm sorry to say it, but Core runners are a dying breed for good reason.

I can definitely recommend Container. It's really the best of both worlds. And with how containers build on each other it's easy to make your own with your persomal tweaks.
