### ISSUE TITLE
Lots of "Client exceeded max pending messages [2]: 512"

### ISSUE THREAD

**Issue by abeksis** [thomasloven/hass-browser_mod#83]
I've been getting frequent bursts of messages like this, and it looks like they may be related to aarlo:

```
2020-04-11 14:44:09 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.23248037430736] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 221, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
jinja2.exceptions.UndefinedError: 'None' has no attribute 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 254, in handle_render_template
    state_listener()
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 242, in state_listener
    msg["id"], {"result": template.async_render(variables)}
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 223, in async_render
    raise TemplateError(err)
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'state'
```
```
2020-04-11 14:50:04 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.23248037430736] Client exceeded max pending messages [2]: 512
2020-04-11 14:50:04 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.23248037430736] Client exceeded max pending messages [2]: 512
2020-04-11 14:50:04 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.23248037430736] Client exceeded max pending messages [2]: 512
2020-04-11 14:50:04 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.23248037430736] Client exceeded max pending messages [2]: 512
2020-04-11 14:50:04 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.23248037430736] Client exceeded max pending messages [2]: 512
2020-04-11 14:50:07 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.23247816134352] Client exceeded max pending messages [2]: 512
2020-04-11 14:50:07 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.23247816134352] Client exceeded max pending messages [2]: 512
2020-04-11 14:50:07 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.23247816134352] Client exceeded max pending messages [2]: 512
```

**Comment by shreram** [comment]
Try to reduce the Jinja templates.  Check this thread (for a different plugin) for background on WebSocket calls.

https://community.home-assistant.io/t/lovelace-button-card/65981/3475

I ran into the same issue with card-mod.

**Comment by thomasloven** [comment]
This issue has grown too old. If this is still a problem, please open a new issue.
